[tool.ruff]
line-length = 88
target-version = "py38"

exclude = [
    ".git", ".hg", ".mypy_cache", ".tox", ".venv",
    "_build", "buck-out", "build", "dist", "venv",
    "logs", "backups", "__pycache__"
]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "C4", "UP"]
ignore = ["E501", "B008"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
